name: "Close stale issues/PR"
on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'No activity recorded in this isssue for the past 60 days. This issue will be closed in 5 days.'
        stale-pr-message: 'No activity recorded in this PR for the past 60 days. This PR will be closed in 5 days.'
        close-issue-message: 'Closing stale issue.' 
        close-pr-message: 'Closing stale PR'
        days-before-stale: 60
        days-before-close: 5
